https:
  port: 8443
  tls:
    "sandbox.api.ultipay.id":
      cert: ./ssl/fullchain.pem
      key: ./ssl/privkey.pem
  options:
    requestCert: false
    rejectUnauthorized: false
# http:
#   port: 8206
#   hostname: localhost
admin:
  port: 8444
  host: "sandbox.api.ultipay.id"
apiEndpoints:
  wallet:
    host: "sandbox.api.ultipay.id"
    paths: "/wallet/*"
  config:
    host: "sandbox.api.ultipay.id"
    paths: "/config/*"
  authentications:
    host: "sandbox.api.ultipay.id"
    paths: "/authentications/*"
  outlet:
    host: "sandbox.api.ultipay.id"
    paths: "/outlet/*"
  account:
    host: "sandbox.api.ultipay.id"
    paths: "/account/*"
  backend:
    host: "sandbox.api.ultipay.id"
    paths: "/backend/*"
  transaction:
    host: "sandbox.api.ultipay.id"
    paths: "/transaction/*"
  paymentGateway:
    host: "sandbox.api.ultipay.id"
    paths: "/paymentGateway/*"
serviceEndpoints:
  wallet:
    url: "http://localhost:8089"
  config:
    url: "http://localhost:8204"
  authentications:
    url: "http://localhost:8202"
  outlet:
    url: "http://localhost:8205"
  account:
    url: "http://localhost:8206"
  backend:
    url: "http://localhost:8203"
  transaction:
    url: "http://localhost:8201"
  paymentGateway:
    url: "http://localhost:8200"
  httpbin:
    url: "https://httpbin.org"
policies:
  - jwt
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - key-auth:
      # - oauth2:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  wallet:
    apiEndpoints:
      - wallet
    policies:
      - rate-limit:
          - action:
              max: 10
              windowMs: 60000
      - proxy:
          - action:
              serviceEndpoint: wallet
              changeOrigin: true

  paymentGateway:
    apiEndpoints:
      - paymentGateway
    policies:
      - rate-limit:
          - action:
              max: 10
              windowMs: 60000
      - proxy:
          - action:
              serviceEndpoint: paymentGateway
              changeOrigin: true

  config:
    apiEndpoints:
      - config
    policies:
      - rate-limit:
          - action:
              max: 10
              windowMs: 60000
      - proxy:
          - action:
              serviceEndpoint: config
              changeOrigin: true

  authentications:
    apiEndpoints:
      - authentications
    policies:
      - rate-limit:
          - action:
              max: 10
              windowMs: 60000
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: authentications
              changeOrigin: true

  outlet:
    apiEndpoints:
      - outlet
    policies:
      - rate-limit:
          - action:
              max: 10
              windowMs: 60000
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: outlet
              changeOrigin: true

  account:
    apiEndpoints:
      - account
    policies:
      - rate-limit:
          - action:
              max: 10
              windowMs: 60000
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: account
              changeOrigin: true
  backend:
    apiEndpoints:
      - backend
    policies:
      - rate-limit:
          - action:
              max: 10
              windowMs: 60000
      - key-auth:
          - action:
              apiKeyHeader: "authorization"
              apiKeyHeaderScheme: "apiKey"
      # - jwt:
      #   - action:
      #       secretOrPublicKeyFile: ./key/pubKey.pem
      #       checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: backend
              changeOrigin: true

  transaction:
    apiEndpoints:
      - transaction
    policies:
      - rate-limit:
          - action:
              max: 10
              windowMs: 60000
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: transaction
              changeOrigin: true
