http:
  port: 8000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  accountService:
    host: 'detik.com'
  api:
    host: localhost
    paths: '/ip'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - oauth2:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
