http:
  port: 8000
admin:
  port: 8001
  host: localhost
apiEndpoints:
  authentication:
    host: localhost
    paths: "/authentications/*"
  outlet:
    host: localhost
    paths: "/outlet/*"
  registration:
    host: localhost
    paths: "/account/registration/*"
  account:
    host: localhost
    paths: "/account/*"
  backend:
    host: "localhost"
    paths: "/backend/*"
  transaction:
    host: "localhost"
    paths: "/transaction/*"
serviceEndpoints:
  authentication:
    url: 'http://localhost:8202'
  outlet:
    url: 'http://localhost:8205'
  registration:
    url: 'http://localhost:8206'
  account:
    url: 'http://localhost:8206'
  backend:
    url: 'http://localhost:8203'
  transaction:
    url: 'http://localhost:8201'
  httpbin:
    url: 'https://httpbin.org'
policies:
  - jwt
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - key-auth:
      # - oauth2:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true

  authentication:
    apiEndpoints:
      - authentication
    policies:
      - rate-limit:
        - action:
            max: 10                      
            windowMs: 120000
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: authentication
              changeOrigin: true
  
  registration:
    apiEndpoints:
      - registration
    policies:
      - rate-limit:
        - action:
            max: 10                      
            windowMs: 120000
      - proxy:
          - action:
              serviceEndpoint: registration
              changeOrigin: true
  
  outlet:
    apiEndpoints:
      - outlet
    policies:
      - rate-limit:
        - action:
            max: 10                      
            windowMs: 120000
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: outlet
              changeOrigin: true

  account:
    apiEndpoints:
      - account
    policies:
      - rate-limit:
        - action:
            max: 10                      
            windowMs: 120000
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: account
              changeOrigin: true
  backend:
    apiEndpoints:
      - backend
    policies:
      - rate-limit:
        - action:
            max: 10                      
            windowMs: 120000
      - key-auth:
        - action:
            apiKeyHeader: "authorization"
            apiKeyHeaderScheme: "apiKey"
      # - jwt:
      #   - action:
      #       secretOrPublicKeyFile: ./key/pubKey.pem
      #       checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: backend
              changeOrigin: true
              
  transaction:
    apiEndpoints:
      - transaction
    policies:
      - rate-limit:
        - action:
            max: 10                      
            windowMs: 120000 
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: transaction
              changeOrigin: true